//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet2_Praya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class evenement
    {
        public short id_evenement { get; set; }
        public System.DateTime date_evenement { get; set; }
        public string desciprtion { get; set; }
        public string lien_evenement { get; set; }
        public short nbr_max_personnes { get; set; }
        public string nom_evenement { get; set; }
        public string statut_evenement { get; set; }
        public string type_evenement { get; set; }
        public string email { get; set; }
    
        public virtual agendum agendum { get; set; }
    }
}
