//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet2_Praya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medium
    {
        public short id_media { get; set; }
        public byte[] media { get; set; }
        public string lien { get; set; }
        public int id_projet { get; set; }
        public string type_media { get; set; }
        public string lib_image { get; set; }
    
        public virtual projet projet { get; set; }
    }
}
