//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet2_Praya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public short id_message { get; set; }
        public string emetteur_email { get; set; }
        public string destinataire_email { get; set; }
        public string libelle { get; set; }
        public string contenu { get; set; }
        public System.DateTime date_creation { get; set; }
        public sbyte top_lu { get; set; }
    }
}
