//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet2_Praya.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projet2Entities : DbContext
    {
        public projet2Entities()
            : base("name=projet2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrateur> administrateurs { get; set; }
        public virtual DbSet<agendum> agenda { get; set; }
        public virtual DbSet<association> associations { get; set; }
        public virtual DbSet<don> dons { get; set; }
        public virtual DbSet<donateur> donateurs { get; set; }
        public virtual DbSet<espace_utilisateur> espace_utilisateur { get; set; }
        public virtual DbSet<evenement> evenements { get; set; }
        public virtual DbSet<facture> factures { get; set; }
        public virtual DbSet<justificatif> justificatifs { get; set; }
        public virtual DbSet<medium> media { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<porfefeuille_factures> porfefeuille_factures { get; set; }
        public virtual DbSet<portefeuille_projet> portefeuille_projet { get; set; }
        public virtual DbSet<preference> preferences { get; set; }
        public virtual DbSet<profil> profils { get; set; }
        public virtual DbSet<projet> projets { get; set; }
        public virtual DbSet<rendez_vous> rendez_vous { get; set; }
        public virtual DbSet<resp_projet> resp_projet { get; set; }
        public virtual DbSet<type_projet> type_projet { get; set; }
        public virtual DbSet<utilisateur> utilisateurs { get; set; }
    }
}
