//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet2_Praya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class porfefeuille_factures
    {
        public short id_portfeuille { get; set; }
        public string libelle { get; set; }
        public short id_don { get; set; }
        public short id_facture { get; set; }
    
        public virtual don don { get; set; }
        public virtual facture facture { get; set; }
    }
}
