//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet2_Praya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class portefeuille_projet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public portefeuille_projet()
        {
            this.projets = new HashSet<projet>();
        }
    
        public short id_portefeuille { get; set; }
        public string resp_projet { get; set; }
        public string libelle { get; set; }
    
        public virtual resp_projet resp_projet1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projet> projets { get; set; }
    }
}
