//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet2_Praya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public projet()
        {
            this.dons = new HashSet<don>();
            this.media = new HashSet<medium>();
        }
    
        public int id_projet { get; set; }
        public string libelle { get; set; }
        public string description { get; set; }
        public string type_du_projet { get; set; }
        public string etat_projet { get; set; }
        public decimal montant_attendu { get; set; }
        public decimal montant_collecte { get; set; }
        public System.DateTime date_butoir { get; set; }
        public System.DateTime date_maj { get; set; }
        public short id_portefeuille { get; set; }
        public System.DateTime date_debut { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<don> dons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medium> media { get; set; }
        public virtual portefeuille_projet portefeuille_projet { get; set; }
        public virtual type_projet type_projet { get; set; }
    }
}
