//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet2_Praya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilisateur
    {
        public string utilisateur_email { get; set; }
        public string mot_de_passe { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public System.DateTime date_maj { get; set; }
    
        public virtual donateur donateur { get; set; }
        public virtual espace_utilisateur espace_utilisateur { get; set; }
    }
}
